version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bsslab-frontend
    ports:
      - "80:80"  # Nginx는 80 포트 사용
    environment:
      - REACT_APP_API_URL=http://203.237.79.121:8080/api  # 백엔드 서버 IP 주소
    restart: always
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge